#!/usr/bin/env bash
# Regenerate docs/cli-reference.md from the live CLI via typer utils docs.
#
# Usage:
#     ./scripts/generate_cli_reference.sh
#
# Requires the project to be installed.
# Works with both `uv` (local dev) and bare `pip install` (CI).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_ROOT}/docs/cli-reference.md"

HEADER="<!-- Auto-generated by scripts/generate_cli_reference.sh — do not edit by hand. -->
<!-- Regenerate: ./scripts/generate_cli_reference.sh -->

# CLI Reference
"

# Use uv if available, otherwise fall back to plain python/typer.
#
# `--extra docs` matters: typer renders option metavars differently across
# releases (`--skip INTEGER` became `--skip <int>`), and the docs extra
# pins the version. Resolving without it would regenerate this file
# against whatever typer happens to be installed, so local output would
# drift from what CI's docs-check expects.
if command -v uv &>/dev/null; then
  BODY="$(uv run --extra docs typer unitysvc.cli utils docs --name usvc)"
else
  BODY="$(python3 -m typer unitysvc.cli utils docs --name usvc)"
fi

printf '%s\n%s\n' "$HEADER" "$BODY" > "$OUT"
echo "Wrote ${OUT} ($(wc -l < "$OUT") lines)"
